project_id = "sfbaltsobmulweapgkco"

[functions.xplane-chat]
verify_jwt = false

[functions.analyze-image]
verify_jwt = false

[functions.session-chat]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.generate-exam]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.purchase-ku]
verify_jwt = false